### ISSUE TITLE
Trust store update notification from DigiCert

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/packed-mn#196] opened 2023-02-09 05:33 UTC
From DigiCert:

This is a reminder that on March 8, 2023, we will begin updating the default public issuance of all TLS/SSL certificate brands to second-generation (G2) root hierarchies.

How does this affect me? 

This change does not affect you if:
* You follow best practices and install the DigiCert-provided ICA certificate with your TLS certificates.

This change does affect you if you do any of the following:
* Pin root or ICA certificates
* Hard-code the acceptance of root or ICA certificates
* Operate a trust store

If you do any of the above, we recommend updating your environment before March 8:
* Stop pinning or hard-coding certificate acceptance.
* Distribute DigiCert G2 roots to the local trust stores to ensure TLS/SSL certificates that chain up to the G2 root certificates are trusted.

**Comment by ronaldtse** [comment] 2023-02-09 05:33
Do we need to update our certificates distributed with packed-mn?

**Comment by CAMOBAP** [comment] 2023-02-09 06:36
@ronaldtse I think this should not affect us.

For OCRA we pack https://curl.se/ca/cacert.pem, to be honest, I didn't know why exactly we are doing this. I have an assumption that this is a workaround for https://github.com/larsch/ocra/issues/128
I think this update will be will handle be handled by person who maintain https://curl.se/ca/cacert.pem

AFAIK for temtebaco we don't include any certs in the image directly.

@maxirmx maybe you have something to add

**Comment by ronaldtse** [comment] 2023-02-09 06:40
I remember we had to pack certificates in packed-mn because the packed executable could not access the system's certificate store. Probably with ruby-packer and maybe https://github.com/larsch/ocra/issues/128.

> I think this update will be will handle be handled by person who maintain https://curl.se/ca/cacert.pem

Yes but we need to rebuild the executable to obtain the latest certificate root collection.

**Comment by ronaldtse** [comment] 2023-02-09 06:41
In Tebako I don't recall whether we can use the system's certificate store. Any comment @maxirmx ?

**Comment by maxirmx** [comment] 2023-02-09 07:55
In tebako we do not anything with certificates. We link libssl, libcrypto and openssl Ruby extension statically and it 'just works'
I assume that it means it can access systems' certificate store 

I am not aware about Ocra certificate issue but I recall that Ocra creates pristine environment as opposed to tebako/ruby-packer that just mount a file system.  This may be the root cause

**Comment by ronaldtse** [comment] 2023-02-10 01:49
This is interesting — I am not sure how OpenSSL staticky compiled under tebako can reuse a macOS trust store, which is stored in the KeyChain. 

For example, people need to manually sync the macOS KeyChain certificate store to OpenSSL like this:
- https://akrabat.com/syncing-macos-keychain-certificates-with-homebrews-openssl/

and Windows uses a different mechanism too. 

It’s not that I don’t believe it uses the systems trust store, I just don’t understand how that can happen. Can we do some investigation here and perhaps that can be a blog post as well?

**Comment by maxirmx** [comment] 2023-05-13 14:52
@ronaldtse 
Tebako uses openssl configuration available at the system. It won't be MacOS KeyChain, it is not compatible as far as I understand. 
Default configuration will be homebrew openssl in most (or all?) cases but openssl extension also picks  OPENSSL_ROOT_DIR environment variable.
Homebrew cert.pem is updated by _brew update_  so we rely on the user ability to keep his MacOS openssl configuration in a good order.

**Comment by ronaldtse** [comment] 2023-05-13 16:05
Question is if someone doesn't have Homebrew installed on macOS, can they not use Tebako / packed-mn?

**Comment by maxirmx** [comment] 2023-05-13 16:23
If someone does not have openssl installed with homebrew or "directly" (like download and build) or they cannot use packed-mn on MacOS.

**Comment by ronaldtse** [comment] 2023-05-14 10:34
If we need to provide the packed-mn executable for someone on a pristine macOS, do we need to bundle OpenSSL, or when you mean “installed”, that includes the default pristine macOS?

**Comment by maxirmx** [comment] 2023-05-14 18:47
- We statically link openssl to packed-mn executable
- We do not bundle openssl configuration or certificates
- Statically linked openssl uses local openssl  certificates.  Practically it means that the system where packed-mn is run needs to have openssl installed

We can probably bundle some knid of private openssl configuration and certificates to tebako package. I do not have an optinion whether it is required or not.

**Comment by maxirmx** [comment] 2023-10-23 20:08
Now I believe that we shall create "private" openssl configuration for tebako packages and emvbed ca-certificates.
There is an example of of a test rub that has an issue since the host system has outdated certificates that do not work for metanorma: https://cirrus-ci.com/task/6596636416147456

This is fixed by ```brew upgrade ca-certificates``` but shall be provided out of 玉手箱

**Comment by maxirmx** [comment] 2023-10-23 20:10
Closed in favor of #215

**Closed by maxirmx** 2023-10-23 20:10 UTC
Labels: enhancement
