### ISSUE TITLE
rouge-4.0.1/lib/rouge/lexers/abap.rb (LoadError)

### ISSUE THREAD

**Issue by CAMOBAP** [metanorma/packed-mn#185] opened 2022-12-20 11:55 UTC
https://github.com/metanorma/packed-mn/actions/runs/3736221016

```
C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge/lexer.rb:532:in `load': cannot load such file -- C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge/lexers/C:/Users/runneradmin/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge/lexers/abap.rb (LoadError)
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge/lexer.rb:532:in `load_lexer'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge.rb:54:in `block in load_lexers'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge.rb:53:in `each'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge.rb:53:in `load_lexers'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge.rb:69:in `<top (required)>'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/isodoc-2.4.1/lib/isodoc/presentation_function/block.rb:2:in `<top (required)>'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/isodoc-2.4.1/lib/isodoc/presentation_xml_convert.rb:1:in `require_relative'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/isodoc-2.4.1/lib/isodoc/presentation_xml_convert.rb:1:in `<top (required)>'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/isodoc-2.4.1/lib/isodoc.rb:23:in `<top (required)>'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/metanorma-1.5.4/lib/metanorma/collection_renderer.rb:3:in `<top (required)>'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/metanorma-1.5.4/lib/metanorma.rb:13:in `<top (required)>'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/metanorma-cli-1.6.9/lib/metanorma/cli.rb:3:in `<top (required)>'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:160:in `rescue in require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:1[49](https://github.com/metanorma/packed-mn/actions/runs/3736221016/jobs/6348027265#step:9:50):in `require'
	from C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/src/metanorma:214:in `<main>'
```

**Comment by ronaldtse** [comment] 2022-12-20 12:50
The rouge gem was added by @opoudjis in the latest version of Metanorma for syntax highlighting, which is causing this error.

**Comment by CAMOBAP** [comment] 2022-12-20 12:55
There is kind of common path processing issue on windows as you may see 

```
C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge/lexers/C:/Users/runneradmin/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge/lexers/abap.rb
```

full path counted twice, probably `relpath` isn't rel actually https://github.com/rouge-ruby/rouge/blob/v4.0.1/lib/rouge/lexer.rb#L529

I will check if possible to "patch" it right in `metanorma` script

**Comment by maxirmx** [comment] 2022-12-25 21:19
The issue is in  https://github.com/rouge-ruby/rouge/blob/master/lib/rouge.rb
```
    # Load the lexers in the `lib/rouge/lexers` directory.
    #
    # @api private
    def load_lexers
      # The trailing slash is necessary to avoid lexers being loaded multiple
      # times by `Lexers.load_lexer`
      lexer_dir = File.join(LIB_DIR, "rouge/lexers/")
      Dir.glob(File.join(lexer_dir, '*.rb')).each do |f|
        Lexers.load_lexer(f.sub(lexer_dir, ''))
      end
    end
```
In this function  on Windows LIB_DIR is 8.3 short name   
``` C:/Users/RUNNER~1/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge/lexers/```   
but Glob returns Windows long name
```C:/Users/runneradmin/AppData/Local/Temp/ocr6B4.tmp/lib/ruby/gems/2.7.0/gems/rouge-4.0.1/lib/rouge/lexers/abap.rb```

So f.sub does not work.

**Comment by CAMOBAP** [comment] 2023-01-04 10:02
Fix for the original gem is provided https://github.com/rouge-ruby/rouge/pull/1911

Still searching for a workaround on our side

**Comment by ronaldtse** [comment] 2023-01-13 04:57
https://github.com/rouge-ruby/rouge/pull/1911 has been merged, so in the next release of rouge we can drop the hack.

**Comment by CAMOBAP** [comment] 2023-02-20 07:45
Rogue 4.1.0 released https://github.com/rouge-ruby/rouge/releases/tag/v4.1.0 workaround can be removed

**Closed** 2023-03-10 19:03 UTC
