### ISSUE TITLE
iso-639 gem language file read issue.

### ISSUE THREAD

**Issue by w00lf** [metanorma/packed-mn#26] opened 2020-04-24 19:30 UTC
Versions of this gem after 0.2.10 all has the issue with reading language file inside compiled applciation. 
```
➜  metanorma-packed git:(master) ✗ ./build/metanorma --type iso -x html ./sources/iso/iso-rice-en.adoc
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/iso-639-0.3.5/lib/iso-639.rb:60:in `block in <class:ISO_639>': undefined method `empty?' for nil:NilClass (NoMethodError)
```

This error occurs in lib/iso-639.rb file during the reading of the language file, for some reason, compiled version reads file partially starting from 31-th line:

```
(byebug) CSV.new(file, **{ col_sep: '|' }).to_a
[["scan languages", "athapascanes, langues"], ["aus", nil, nil, "Australian languages", "australiennes, langues"], ["ava", nil, "av", "Avaric", "avar"], ["ave", nil, "ae", "Avestan", "avestique"], ["awa", nil, nil, "Awadhi", "awadhi"],
```

**Comment by ronaldtse** [comment] 2020-04-24 19:57
No idea why... Can we use this instead of the foreign `iso-639` gem?

* https://github.com/glossarist/iev-data/blob/master/lib/iev/termbase/iso_639_code.rb
* https://github.com/glossarist/iev-data/blob/master/lib/iev/termbase/iso_639_2.yaml

We could move this to new gem too.

**Comment by CAMOBAP** [comment] 2020-06-06 18:23
@w00lf @ronaldtse I cannot reproduce the original error, but when I run `./build/metanorma --type iso -x html ./sources/iso/iso-rice-en.adoc`

It ends with:
```
Error: File to import not found or unreadable: base_style/all.
        on line 13:1 of stdin
>> @import 'base_style/all';

   ^
```

Should we investigate this problem in the scope of this task?

**Comment by ronaldtse** [comment] 2020-06-07 07:23
@CAMOBAP this is the issue with SASSC, that was the reason of the sassc fork. If the binary is failing, how can the builds be passing now?

**Comment by ronaldtse** [comment] 2020-06-07 07:23
I really think we should get rid of sassc using this: https://github.com/metanorma/metanorma/issues/109

**Comment by CAMOBAP** [comment] 2020-06-07 08:23
> @CAMOBAP this is the issue with SASSC, that was the reason of the sassc fork. If the binary is failing, how can the builds be passing now?

Good question, because `metanorma` returns zero exit code, and we check only exit code.
In my opinion, we should fix this, @ronaldtse how do you think?

**Comment by CAMOBAP** [comment] 2020-06-26 03:44
Just reproduced original problem somehow:

```
/__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/iso-639-0.3.5/lib/iso-639.rb:60:in `block in <class:ISO_639>': undefined method `empty?' for nil:NilClass (NoMethodError)
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/iso-639-0.3.5/lib/iso-639.rb:59:in `collect'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/iso-639-0.3.5/lib/iso-639.rb:59:in `<class:ISO_639>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/iso-639-0.3.5/lib/iso-639.rb:5:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-1.0.10/lib/asciidoctor/nist/front_id.rb:1:in `require'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-1.0.10/lib/asciidoctor/nist/front_id.rb:1:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-1.0.10/lib/asciidoctor/nist/front.rb:4:in `require_relative'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-1.0.10/lib/asciidoctor/nist/front.rb:4:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-1.0.10/lib/asciidoctor/nist/converter.rb:6:in `require_relative'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-1.0.10/lib/asciidoctor/nist/converter.rb:6:in `<top (required)>'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-1.0.10/lib/metanorma-nist.rb:2:in `require_relative'
	from /__enclose_io_memfs__/local/vendor/bundle/ruby/2.4.0/gems/metanorma-nist-1.0.10/lib/metanorma-nist.rb:2:in `<top (required)>'
	from /__enclose_io_memfs__/local/metanorma:129:in `require'
	from /__enclose_io_memfs__/local/metanorma:129:in `<main>'
```

**Comment by ronaldtse** [comment] 2021-12-05 06:29
Not seeing this anymore. Closing.

**Closed by ronaldtse** 2021-12-05 06:29 UTC
Labels: bug
